// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm6pBqFBTJHyHiZCG35eNzoRqMBj7FQII',
    appId: '1:155550854173:web:fa562e9a9b4f9321c76af4',
    messagingSenderId: '155550854173',
    projectId: 'uts-alatpancing',
    authDomain: 'uts-alatpancing.firebaseapp.com',
    storageBucket: 'uts-alatpancing.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMDW_F-SMe-ctj3d5-mxWJWY7VZNGnHt4',
    appId: '1:155550854173:android:70297cb94fda2fa7c76af4',
    messagingSenderId: '155550854173',
    projectId: 'uts-alatpancing',
    storageBucket: 'uts-alatpancing.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm6pBqFBTJHyHiZCG35eNzoRqMBj7FQII',
    appId: '1:155550854173:web:ce569e8556da0c54c76af4',
    messagingSenderId: '155550854173',
    projectId: 'uts-alatpancing',
    authDomain: 'uts-alatpancing.firebaseapp.com',
    storageBucket: 'uts-alatpancing.firebasestorage.app',
  );
}
